version: 1.0

deploy:
  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - mkdir $GITHUB_WORKSPACE/storage/logs
      - php $GITHUB_WORKSPACE/artisan down
      - find $GITHUB_WORKSPACE -type f -not -path "$GITHUB_WORKSPACE/logs/*" -exec chmod 664 {} \;
      - find $GITHUB_WORKSPACE -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w $GITHUB_WORKSPACE/storage $GITHUB_WORKSPACE/bootstrap/cache
      - php $GITHUB_WORKSPACE/artisan optimize:clear
      - php $GITHUB_WORKSPACE/artisan migrate --force -n
      - php $GITHUB_WORKSPACE/artisan storage:link
      - php $GITHUB_WORKSPACE/artisan optimize
      - php $GITHUB_WORKSPACE/artisan up

  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - php $GITHUB_WORKSPACE/artisan down
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - find $GITHUB_WORKSPACE -type f -not -path "$GITHUB_WORKSPACE/logs/*" -exec chmod 664 {} \;
      - find $GITHUB_WORKSPACE -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w $GITHUB_WORKSPACE/storage $GITHUB_WORKSPACE/bootstrap/cache
      - php $GITHUB_WORKSPACE/artisan optimize:clear
      - php $GITHUB_WORKSPACE/artisan migrate --force -n
      - php $GITHUB_WORKSPACE/artisan storage:link
      - php $GITHUB_WORKSPACE/artisan optimize
      - php $GITHUB_WORKSPACE/artisan up
