name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Setup Laravel environment
      run: php artisan down

    - name: Apply file permissions
      run: |
        mkdir -p storage/logs
        find . -type f -not -path "./storage/logs/*" -exec chmod 664 {} \;
        find . -type d -not -name "logs" -exec chmod 775 {} \;
        chmod -R o+w storage bootstrap/cache

    - name: Clear optimization cache
      run: php artisan optimize:clear

    - name: Run database migrations
      run: php artisan migrate --force -n

    - name: Create symbolic link for storage
      run: php artisan storage:link

    - name: Optimize application
      run: php artisan optimize

    - name: Bring Laravel application back up
      run: php artisan up
